name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.6'

      - name: Build Go binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o myapp main.go

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: myapp
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



